// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of command execution
 */
export type AckResult = "Ok" | { "Error": { message: string, } } | "Pending";
