// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Easing } from "./Easing";
import type { Keyframe } from "./Keyframe";

/**
 * Animation configuration bound to a progress value
 */
export type AnimationBinding = { 
/**
 * Path to the progress value (0.0 - 1.0)
 */
progress_bind: string, 
/**
 * Easing function
 */
easing: Easing, 
/**
 * Keyframes defining the animation
 */
keyframes: Array<Keyframe>, };
