// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Backoff strategy for retries
 */
export type BackoffStrategy = "Fixed" | "Exponential" | "Jitter";
