// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AlignItems } from "./AlignItems";
import type { EdgeInsets } from "./EdgeInsets";
import type { FlexDirection } from "./FlexDirection";
import type { JustifyContent } from "./JustifyContent";
import type { LayoutValue } from "./LayoutValue";
import type { Overflow } from "./Overflow";
import type { Position } from "./Position";

/**
 * Layout style configuration (Flexbox-based)
 */
export type LayoutStyle = { 
/**
 * Width
 */
width: LayoutValue, 
/**
 * Height
 */
height: LayoutValue, 
/**
 * Minimum width
 */
min_width: LayoutValue | null, 
/**
 * Maximum width
 */
max_width: LayoutValue | null, 
/**
 * Minimum height
 */
min_height: LayoutValue | null, 
/**
 * Maximum height
 */
max_height: LayoutValue | null, 
/**
 * Flex direction
 */
flex_direction: FlexDirection, 
/**
 * Flex grow factor
 */
flex_grow: number, 
/**
 * Flex shrink factor
 */
flex_shrink: number, 
/**
 * Gap between children
 */
gap: number, 
/**
 * Justify content (main axis)
 */
justify: JustifyContent, 
/**
 * Align items (cross axis)
 */
align: AlignItems, 
/**
 * Padding
 */
padding: EdgeInsets, 
/**
 * Margin
 */
margin: EdgeInsets, 
/**
 * Overflow behavior
 */
overflow: Overflow, 
/**
 * Position type
 */
position: Position, };
