// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Overflow behavior
 */
export type Overflow = "Visible" | "Hidden" | "Scroll" | "Auto";
