// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Portal target layer
 */
export type PortalTarget = "Overlay" | "Tooltip" | "Dropdown" | { "Custom": number };
