// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AckResult } from "./AckResult";

/**
 * Acknowledgment from Bevy for a command
 */
export type UiAck = { 
/**
 * Sequence number of the acknowledged command
 */
seq: bigint, 
/**
 * Result of command execution
 */
result: AckResult, };
