// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../../serde_json/JsonValue";
import type { UiNode } from "./UiNode";

/**
 * A state change notification from Bevy to React
 */
export type UiPatch = { "Set": { path: string, value: JsonValue, } } | { "SetBatch": { updates: Array<[string, JsonValue]>, } } | { "NodeSet": { id: bigint, node: UiNode, } } | { "NodeRemove": { id: bigint, } } | { "NodeMove": { id: bigint, new_parent: bigint, index: number, } } | { "NodePropUpdate": { id: bigint, props: JsonValue, } } | { "FullSync": { 
/**
 * All binding values
 */
bindings: { [key in string]?: JsonValue }, 
/**
 * Complete node tree
 */
nodes: Array<UiNode>, 
/**
 * Current sequence number
 */
seq: bigint, } } | { "FocusChange": { 
/**
 * New focused node (None = nothing focused)
 */
node_id: bigint | null, } } | { "UndoStateChange": { can_undo: boolean, can_redo: boolean, undo_label: string | null, redo_label: string | null, } };
