// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActiveTool } from "./ActiveTool";

/**
 * Overall viewport state
 */
export type ViewportState = { active_tool: ActiveTool, camera_position: [number, number, number], camera_target: [number, number, number], };
