// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Async value state (for bindings)
 */
export type AsyncValue<T> = "Loading" | { "Ready": T } | { "Error": { message: string, } };
