// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Easing function
 */
export type Easing = "Linear" | "EaseIn" | "EaseOut" | "EaseInOut" | "EaseInCubic" | "EaseOutCubic" | "EaseInOutCubic" | "EaseInQuad" | "EaseOutQuad" | "EaseInOutQuad" | "EaseInBack" | "EaseOutBack" | "EaseInOutBack" | "EaseInElastic" | "EaseOutElastic" | "Spring";
