// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Layout dimension value
 */
export type LayoutValue = "Auto" | { "Percent": number } | { "Pixels": number } | "Fill";
