// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../../serde_json/JsonValue";

/**
 * A user intent sent from React to Bevy
 * 
 * Commands never mutate state directly - they express INTENT.
 * Bevy decides how to handle them.
 */
export type UiCommand = { 
/**
 * Command type (e.g., "SetBrushRadius", "SelectLayer", "ToggleVisibility")
 */
cmd: string, 
/**
 * Command arguments (type depends on cmd)
 */
args: JsonValue, 
/**
 * Transaction ID for undo grouping
 * Same tx = undo together (e.g., all moves in one drag session)
 */
tx: string | null, 
/**
 * Sequence number for ordering and acknowledgment
 */
seq: bigint, 
/**
 * Source node ID (which UI element triggered this)
 */
source: bigint | null, };
