// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AsyncConfig } from "./AsyncConfig";
import type { CommandBinding } from "./CommandBinding";
import type { FocusConfig } from "./FocusConfig";
import type { JsonValue } from "../../serde_json/JsonValue";
import type { LayoutStyle } from "./LayoutStyle";
import type { PortalConfig } from "./PortalConfig";
import type { SlotDefinition } from "./SlotDefinition";

/**
 * A UI node that maps to a React component
 */
export type UiNode = { 
/**
 * Unique identifier (usually Entity.to_bits())
 */
id: bigint, 
/**
 * React component to render (e.g., "Slider", "Button", "Panel")
 */
component: string, 
/**
 * Parent node ID (None = root node)
 */
parent: bigint | null, 
/**
 * Static props passed to the component
 */
props: JsonValue, 
/**
 * Reactive bindings: prop_name → binding_path
 * Example: { "value": "brush.radius", "disabled": "!ui.canSculpt" }
 */
bindings: { [key in string]?: string }, 
/**
 * Command mappings: event_name → CommandBinding
 * Example: { "onChange": { cmd: "SetBrushRadius", ... } }
 */
commands: { [key in string]?: CommandBinding }, 
/**
 * Layout style hints
 */
layout: LayoutStyle | null, 
/**
 * Focus/tab navigation configuration
 */
focus: FocusConfig | null, 
/**
 * Portal configuration (for modals/overlays)
 */
portal: PortalConfig | null, 
/**
 * Target slot to fill (for child nodes)
 * Example: "right_panel", "header"
 */
target_slot: string | null, 
/**
 * Named slots this node defines (for layout containers)
 */
slots: Array<SlotDefinition> | null, 
/**
 * Async/loading state configuration
 */
async_config: AsyncConfig | null, };
