// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UiPatch } from "./UiPatch";

/**
 * A batch of patches (for efficient network transmission)
 */
export type UiPatchBatch = { 
/**
 * The patches in this batch
 */
patches: Array<UiPatch>, 
/**
 * Sequence number for ordering
 */
seq: bigint, 
/**
 * Timestamp for debugging
 */
timestamp: number, };
