// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../../serde_json/JsonValue";
import type { RetryConfig } from "./RetryConfig";

/**
 * Async loading/error configuration
 */
export type AsyncConfig = { 
/**
 * Component to show while loading
 */
loading: string | null, 
/**
 * Component to show on error
 */
error: string | null, 
/**
 * Props for loading component
 */
loading_props: JsonValue, 
/**
 * Retry configuration
 */
retry: RetryConfig | null, 
/**
 * Timeout in milliseconds
 */
timeout_ms: number | null, };
