// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../../serde_json/JsonValue";

/**
 * A keyframe in an animation
 */
export type Keyframe = { 
/**
 * Position in animation (0.0 - 1.0)
 */
at: number, 
/**
 * Props at this keyframe
 */
props: JsonValue, };
