// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BackdropConfig } from "./BackdropConfig";
import type { DismissTrigger } from "./DismissTrigger";
import type { PortalPosition } from "./PortalPosition";
import type { PortalTarget } from "./PortalTarget";

/**
 * Portal configuration for out-of-tree rendering
 */
export type PortalConfig = { 
/**
 * Portal target layer
 */
target: PortalTarget, 
/**
 * Z-index (higher = on top)
 */
z_index: number, 
/**
 * Positioning strategy
 */
position: PortalPosition, 
/**
 * Trap focus inside portal
 */
focus_trap: boolean, 
/**
 * Auto-dismiss triggers
 */
dismiss_on: Array<DismissTrigger>, 
/**
 * Backdrop (darken background)
 */
backdrop: BackdropConfig | null, };
