// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Virtual scroll report from React to Bevy
 */
export type VirtualScrollReport = { 
/**
 * List node ID
 */
list_id: bigint, 
/**
 * First visible index
 */
start_index: number, 
/**
 * Last visible index (exclusive)
 */
end_index: number, 
/**
 * Scroll position (pixels from top)
 */
scroll_top: number, 
/**
 * Viewport height
 */
viewport_height: number, };
