[package]
name = "k-os-renderer"
version = "0.1.0"
edition = "2021"

[dependencies]
crossbeam-channel = "0.5"
glam = { version = "0.30", features = ["serde", "bytemuck"] }
k-os-gpu-pipeline = { path = "../k-os-gpu-pipeline" }
 k-os-eval = { path = "../k-os-eval" }
 k-os-kain = { path = "../k-os-kain" }
 k-os-mesh-processing = { path = "../k-os-mesh-processing" }
k-os-scene = { path = "../k-os-scene" }
naga = { version = "26", features = ["spv-in", "wgsl-out"] }
parking_lot = "0.12"
pollster = "0.4.0"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
wgpu = "26"
