// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Anchor } from "./Anchor";

/**
 * How to position the portal
 */
export type PortalPosition = { "Fixed": { x: number, y: number, } } | "Cursor" | { "RelativeTo": { node_id: bigint, anchor: Anchor, } } | "Center";
