// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BackoffStrategy } from "./BackoffStrategy";

/**
 * Retry configuration for failed async operations
 */
export type RetryConfig = { 
/**
 * Maximum retry attempts
 */
max_attempts: number, 
/**
 * Initial delay between retries (ms)
 */
delay_ms: number, 
/**
 * Backoff strategy
 */
backoff: BackoffStrategy, };
