// Generated by KAIN compiler
// Target: TypeScript (strict)
/* eslint-disable @typescript-eslint/no-explicit-any */

// Numeric type helpers
function u8(n: number): number { return n & 0xFF; }
function u16(n: number): number { return n & 0xFFFF; }
function u32(n: number): number { return n >>> 0; }
function i8(n: number): number { return (n << 24) >> 24; }
function i16(n: number): number { return (n << 16) >> 16; }
function i32(n: number): number { return n | 0; }
function f32(n: number): number { return Math.fround(n); }

// Low-level memory emulation runtime
type __KainPtrMeta = { kind: "value" } | { kind: "field"; base: number; field: string } | { kind: "index"; base: number; index: number };
const __kainMem = new Map<number, any>();
const __kainPtrMeta = new Map<number, __KainPtrMeta>();
let __kainNextPtr = 1;
function __kain_new_ptr(meta: __KainPtrMeta): number { const ptr = __kainNextPtr++; __kainPtrMeta.set(ptr, meta); return ptr; }
function __kain_clone_value<T>(value: T): T { if (Array.isArray(value)) { return value.map((item) => __kain_clone_value(item)) as T; } if (value && typeof value === "object") { return Object.fromEntries(Object.entries(value as Record<string, unknown>).map(([k, v]) => [k, __kain_clone_value(v)])) as T; } return value; }
function __kain_addr_of<T>(value: T): number { const ptr = __kain_new_ptr({ kind: "value" }); __kainMem.set(ptr, value); return ptr; }
function __kain_bind_local<T>(value: T): number { return __kain_addr_of(value); }
function __kain_field_ptr(ptr: number, field: string, _offset: number): number { return __kain_new_ptr({ kind: "field", base: ptr, field }); }
function __kain_index_ptr(ptr: number, index: number, _stride: number): number { return __kain_new_ptr({ kind: "index", base: ptr, index }); }
function __kain_ptr_offset(ptr: number, offset: number, stride: number): number { return ptr + (offset * Math.max(stride, 1)); }
function __kain_mem_load<T>(ptr: number): T { const meta = __kainPtrMeta.get(ptr); if (!meta || meta.kind === "value") { return __kainMem.get(ptr) as T; } if (meta.kind === "field") { const base = __kain_mem_load<any>(meta.base); return base?.[meta.field] as T; } const base = __kain_mem_load<any>(meta.base); return base?.[meta.index] as T; }
function __kain_mem_store<T>(ptr: number, value: T): T { const meta = __kainPtrMeta.get(ptr); if (!meta || meta.kind === "value") { __kainMem.set(ptr, value); return value; } if (meta.kind === "field") { const base = __kain_mem_load<any>(meta.base); if (base != null) { base[meta.field] = value; } return value; } const base = __kain_mem_load<any>(meta.base); if (base != null) { base[meta.index] = value; } return value; }
function __kain_union_buffer(value: any, size: number): ArrayBuffer { if (!value || typeof value !== "object") { return new ArrayBuffer(Math.max(size, 1)); } if (!Object.prototype.hasOwnProperty.call(value, "__kain_union_buffer")) { Object.defineProperty(value, "__kain_union_buffer", { value: new ArrayBuffer(Math.max(size, 1)), writable: true, enumerable: false, configurable: true }); } const existing = value.__kain_union_buffer as ArrayBuffer; if (existing.byteLength < Math.max(size, 1)) { const next = new ArrayBuffer(Math.max(size, 1)); new Uint8Array(next).set(new Uint8Array(existing.slice(0))); Object.defineProperty(value, "__kain_union_buffer", { value: next, writable: true, enumerable: false, configurable: true }); return next; } return existing; }
function __kain_union_encode(view: DataView, typeKey: string, byteSize: number, value: any): void { switch (typeKey) { case "Float": if (byteSize >= 8) { view.setFloat64(0, Number(value ?? 0), true); } else { view.setFloat32(0, Number(value ?? 0), true); } break; case "Bool": view.setUint8(0, value ? 1 : 0); break; case "Char": view.setUint8(0, typeof value === "string" && value.length > 0 ? value.charCodeAt(0) & 0xFF : 0); break; default: if (byteSize >= 8) { view.setBigInt64(0, BigInt(Math.trunc(Number(value ?? 0))), true); } else if (byteSize >= 4) { view.setInt32(0, Number(value ?? 0), true); } else if (byteSize >= 2) { view.setInt16(0, Number(value ?? 0), true); } else { view.setInt8(0, Number(value ?? 0)); } break; } }
function __kain_union_decode(typeKey: string, byteSize: number, fallback: any, view: DataView): any { switch (typeKey) { case "Float": return byteSize >= 8 ? view.getFloat64(0, true) : view.getFloat32(0, true); case "Bool": return view.getUint8(0) !== 0; case "Char": return String.fromCharCode(view.getUint8(0)); default: if (byteSize >= 8) { return Number(view.getBigInt64(0, true)); } if (byteSize >= 4) { return view.getInt32(0, true); } if (byteSize >= 2) { return view.getInt16(0, true); } if (byteSize >= 1) { return view.getInt8(0); } return fallback; } }
function __kain_union_wrap<T extends object>(value: T, active: string, typeKey: string, byteSize: number, unionSize: number, activeValue: any): T { Object.defineProperty(value, "__kain_union_active", { value: active, writable: true, enumerable: false, configurable: true }); const buffer = __kain_union_buffer(value, unionSize); const view = new DataView(buffer); __kain_union_encode(view, typeKey, byteSize, activeValue); return value; }
function __kain_union_get<T>(value: any, field: string, typeKey: string, byteSize: number, unionSize: number, fallback: T): T { if (value == null) { return fallback; } if (value.__kain_union_active === field) { return value[field] as T; } const buffer = __kain_union_buffer(value, unionSize); const next = __kain_union_decode(typeKey, byteSize, fallback, new DataView(buffer)) as T; value[field] = next; return next; }
function __kain_union_set<T>(value: any, field: string, typeKey: string, byteSize: number, unionSize: number, next: T): T { if (value != null) { const buffer = __kain_union_buffer(value, unionSize); __kain_union_encode(new DataView(buffer), typeKey, byteSize, next); value[field] = next; Object.defineProperty(value, "__kain_union_active", { value: field, writable: true, enumerable: false, configurable: true }); } return next; }
function __kain_bitfield_units(value: any): Record<string, number> { if (value == null) { return {}; } if (!Object.prototype.hasOwnProperty.call(value, "__kain_bitfield_units")) { Object.defineProperty(value, "__kain_bitfield_units", { value: {}, writable: true, enumerable: false, configurable: true }); } return value.__kain_bitfield_units as Record<string, number>; }
function __kain_bitfield_get(value: any, field: string, unitOffset: number, bitOffset: number, width: number, signed: boolean): number { if (value == null) { return 0; } const units = __kain_bitfield_units(value) as Record<string, bigint>; const key = String(unitOffset); const unit = BigInt(units[key] ?? 0n); const safeWidth = BigInt(Math.max(width, 0)); const shift = BigInt(Math.max(bitOffset, 0)); const mask = safeWidth === 0n ? 0n : ((1n << safeWidth) - 1n); let next = Number((unit >> shift) & mask); if (signed && width > 0) { const signBit = 1n << BigInt(width - 1); let signedValue = (unit >> shift) & mask; if ((signedValue & signBit) !== 0n) { signedValue -= (1n << BigInt(width)); } next = Number(signedValue); } value[field] = next; return next; }
function __kain_bitfield_set(value: any, field: string, unitOffset: number, bitOffset: number, width: number, signed: boolean, next: number): number { if (value == null) { return next; } const units = __kain_bitfield_units(value) as Record<string, bigint>; const key = String(unitOffset); const unit = BigInt(units[key] ?? 0n); const safeWidth = BigInt(Math.max(width, 0)); const shift = BigInt(Math.max(bitOffset, 0)); const mask = safeWidth === 0n ? 0n : ((1n << safeWidth) - 1n); let encoded = BigInt(Math.trunc(Number(next))); if (safeWidth > 0n) { encoded &= mask; } const cleared = unit & ~(mask << shift); units[key] = cleared | ((encoded & mask) << shift); const normalized = __kain_bitfield_get(value, field, unitOffset, bitOffset, width, signed); return normalized; }
function __kain_alloc(size: number, stride: number, _zeroed: boolean, seed: any): number { const step = Math.max(stride, 1); const count = Math.max(1, Math.ceil(Math.max(size, step) / step)); const base = __kainNextPtr; for (let i = 0; i < count; i++) { __kainMem.set(base + (i * step), __kain_clone_value(seed)); } __kainNextPtr = base + (count * step); return base; }
function __kain_realloc(ptr: number, size: number, stride: number, seed: any): number { if (!ptr) { return __kain_alloc(size, stride, false, seed); } const step = Math.max(stride, 1); const count = Math.max(1, Math.ceil(Math.max(size, step) / step)); for (let i = 0; i < count; i++) { const nextPtr = ptr + (i * step); if (!__kainMem.has(nextPtr)) { __kainMem.set(nextPtr, __kain_clone_value(seed)); } } return ptr; }

export interface SculptLayerShape {
  id: string;
  name: string;
  mesh: THREE_Mesh;
  visible: boolean;
  polyCount: number;
  materialId: Option<string>;
}
export class SculptLayer implements SculptLayerShape {
  id: string;
  name: string;
  mesh: THREE_Mesh;
  visible: boolean;
  polyCount: number;
  materialId: Option<string>;
  
  constructor(id: string = "", name: string = "", mesh: THREE_Mesh = null as any, visible: boolean = false, polyCount: number = 0, materialId: Option<string> = null as any) {
    this.id = id;
    this.name = name;
    this.mesh = mesh;
    this.visible = visible;
    this.polyCount = polyCount;
    this.materialId = materialId;
  }
}

export function KSculpt(arg_1: Any): void {
useEffect(null, [useKainShaders, activeBrush])  ;
let orbitRef = useRef(null)  ;
let lastRot = useRef(null)  ;
let sculptQuickMenuCommands = React.useMemo(null, [])  ;
useRegisterQuickMenuCommands("ksculpt", sculptQuickMenuCommands)  ;
let mousePosRef = useRef(null)  ;
let qKeyActiveRef = React.useRef(false)  ;
useEffect(null, [isSpaceMenuLocked])  ;
let handleGlobalMouseMove = null  ;
useEffect(null, [])  ;
useEffect(null, [])  ;
let sceneRef = useRef(null)  ;
useEffect(null, [useNativeRenderer])  ;
let activeNativeMeshHandle = React.useMemo(null, [activeLayerId, layers])  ;
let nativeSyncSource = React.useMemo(null, [activeNativeMeshHandle])  ;
let getActiveNativeMesh = React.useCallback(null, [activeLayerId])  ;
let syncActiveMeshToNativeRenderer = React.useCallback(null, [getActiveNativeMesh, useNativeRenderer])  ;
let applyNativeSelectionBrush = React.useCallback(null, [activeAlpha.handle, activeTool, brushMode, getActiveNativeMesh, intensity, radius, symmetry])  ;
useEffect(null, [useNativeRenderer, activeLayerId, syncActiveMeshToNativeRenderer])  ;
let fluxMesh = (null)()  ;
let flux = useFlux(null)  ;
let immDefaultMaterialRef = useRef(THREE.MeshStandardMaterial(null))  ;
let prevMaterialModeRef = useRef("CLAY")  ;
let prevActiveMaterialRef = useRef(null)  ;
let altOrbitEnabledRef = useRef(false)  ;
let ensureSculptGeometryAttributes = null  ;
let activePolyCount = ((layers.find(null) ?? null.polyCount || 0))  ;
let mountRef = useRef(null)  ;
let stageRef = useRef(null)  ;
useEffect(null, [])  ;
useEffect(null, [activeTool, radius, intensity, symmetry, mode, activeLayerId, activeMaterial, brushMode, activeAlpha, dynamicTopology, detailSize, activeColor, isSceneReady, isBevyActive, activeBrush])  ;
useEffect(null, [activeBrush.id])  ;
let getActiveMesh = React.useCallback(null, [layers, activeLayerId])  ;
let getSubdivisionLevel = React.useCallback(null, [subdivisionLevel])  ;
let handleIMMUpdate = React.useCallback(null, [activeLayerId])  ;
useIMMInteraction(null)  ;
useEffect(null, [showGrid, sceneRef.current.scene])  ;
useEffect(null, [])  ;
useEffect(null, [])  ;
useEffect(null, [useNativeRenderer])  ;
useEffect(null, [useNativeRenderer])  ;
useEffect(null, [gizmoMode, transformSpace, snapEnabled])  ;
let addMeshToScene = null  ;
useEffect(null, [appMode])  ;
let mergeMeshes = null  ;
let handleMergeDown = null  ;
let handleMergeSelected = null  ;
let handleMergeAll = null  ;
let handleSubdivide = null  ;
let handleApplyMaterial = null  ;
let updateMeshMaterial = null  ;
let handleOpenKainAuthoring = React.useCallback(null, [activeBrush])  ;
useEffect(null, [appMode, materialMode, layers, sharedState.materials, currentMatCap])  ;
useEffect(null, [wireframe, layers])  ;
let handleLayerSelect = null  ;
let handleFrameActive = null  ;
let handleCycleLayer = null  ;
let loadPrimitive = null  ;
let loadFromStorage = null  ;
((window).ksculptSceneRef = sceneRef)  ;
((window).ksculptActiveLayerId = activeLayerId)  ;
let saveHistory = null  ;
((window).ksculptSaveHistory = saveHistory)  ;
let undo = null  ;
let handleStepUp = null  ;
let updateTransformFromUI = null  ;
let onPointerMove = null  ;
useEffect(null, [mode])  ;
let onPointerDown = null  ;
let onPointerUp = null  ;
let applyBrush = null  ;
let executeBrushStamp = null  ;
useGlobalHotkeys(null, true)  ;
let commitToKernel = null  ;
let handleToggleVis = null  ;
let handleDeleteLayer = null  ;
let clearMask = null  ;
let invertMask = null  ;
let extractMask = null  ;
let handleVoxelRemesh = null  ;
let handleGpuDynamesh = null  ;
useEffect(null, [activeLayerId, mode])  ;
let handleUplink = null  ;
return (AppShell({layoutKey: 'ksculpt', className: null, menuBar: AppMenuBar({menus: [null, null, null, null]}), menuBarDefaultOpen: false, topBar: TopBar({appMode: appMode, setAppMode: setAppMode, activeBrush: activeBrush, setActiveBrush: setActiveBrush, brushesLoaded: brushesLoaded, radius: radius, setRadius: setRadius, intensity: intensity, setIntensity: setIntensity, brushMode: brushMode, setBrushMode: setBrushMode, symmetry: symmetry, setSymmetry: setSymmetry, wireframe: wireframe, setWireframe: setWireframe, dynamicTopology: dynamicTopology, setDynamicTopology: setDynamicTopology, detailSize: detailSize, setDetailSize: setDetailSize, currentMatCap: currentMatCap, setCurrentMatCap: setCurrentMatCap, showGrid: showGrid, setShowGrid: setShowGrid, useKainShaders: useKainShaders, setUseKainShaders: setUseKainShaders, pipelineStatus: pipelineStatus, onOpenKainAuthoring: handleOpenKainAuthoring, onUplink: handleUplink, fluxActive: fluxActive, onFluxToggle: null}), left: null, right: null, children: [(() => {    
    const __el = document.createElement('div');
    __el.setAttribute('className', 'relative h-full w-full bg-black cursor-crosshair');
__el.setAttribute('onDragOver', String(null    ));
__el.setAttribute('onDrop', String(null    ));
__el.appendChild((() => {      
      const __el = document.createElement('div');
__el.setAttribute('ref', String(mountRef      ));
__el.setAttribute('className', String(null      ));
__el.setAttribute('onPointerDown', String(onPointerDown      ));
__el.setAttribute('onPointerMove', String(onPointerMove      ));
__el.setAttribute('onPointerUp', String(onPointerUp      ));
__el.setAttribute('onPointerLeave', String(onPointerUp      ));
      return __el;
})()    );
__el.appendChild((() => {      
if (useNativeRenderer      ) {
return NativeViewport({meshHandle: activeNativeMeshHandle, useSculptHandle: true, syncSource: nativeSyncSource, hostInputMode: 'camera+cursor', onSelectionChange: null, onStrokeStart: null, onStrokeMove: null, onStrokeEnd: null, onStatusChange: null})        ;
      }
      return document.createTextNode('');
})()    );
__el.appendChild(ScreenspaceCursor({radius: radius, camera: ((sceneRef.current.camera || null)), visible: ((((((((isSceneReady && ((mode === "SCULPT")))) && ((activeTool !== "SELECT")))) && ((!isBevyActive)))) && ((!useNativeRenderer)))), isActive: ((sceneRef.current.isSculpting || false)), symmetry: symmetry, mountRef: mountRef, color: '#ff8c00'})    );
__el.appendChild(KSculptQuickMenu({open: isSpaceMenuOpen, onOpenChange: setIsSpaceMenuOpen, activeBrush: activeBrush, setActiveBrush: setActiveBrush, intensity: intensity, setIntensity: setIntensity, radius: radius, setRadius: setRadius, gpuMode: simGpuMode, setGpuMode: setSimGpuMode, pinned: isSpaceMenuLocked, setPinned: setIsSpaceMenuLocked, onReset: null})    );
__el.appendChild((() => {      
      const __el = document.createElement('div');
      __el.setAttribute('className', 'absolute top-20 left-6 flex flex-col gap-2 pointer-events-none');
__el.appendChild((() => {        
        const __el = document.createElement('div');
        __el.setAttribute('className', 'flex items-center gap-2 text-[10px] font-bold text-orange-500 bg-black/80 px-4 py-2 border-l-2 border-orange-500 shadow-xl backdrop-blur-md');
__el.appendChild(Activity({size: 12, className: 'animate-pulse'})        );
__el.appendChild((() => {          
const __val = status          ;
          if (typeof __val === 'string' || typeof __val === 'number') {
            return document.createTextNode(String(__val));
          } else if (__val instanceof Node) {
            return __val;
          } else {
            return document.createTextNode('');
          }
})()        );
        return __el;
})()      );
__el.appendChild((() => {        
        const __el = document.createElement('div');
        __el.setAttribute('className', 'pointer-events-auto');
__el.appendChild((() => {          
          const __el = document.createElement('button');
          __el.setAttribute('type', 'button');
__el.setAttribute('onClick', String(null          ));
__el.setAttribute('className', String(null          ));
__el.appendChild((() => {            
if (useNativeRenderer            ) {
return (() => {                
const __val = "NATIVE VIEWPORT: ON"                ;
                if (typeof __val === 'string' || typeof __val === 'number') {
                  return document.createTextNode(String(__val));
                } else if (__val instanceof Node) {
                  return __val;
                } else {
                  return document.createTextNode('');
                }
})()              ;
            } else {
return (() => {                
const __val = "NATIVE VIEWPORT: OFF"                ;
                if (typeof __val === 'string' || typeof __val === 'number') {
                  return document.createTextNode(String(__val));
                } else if (__val instanceof Node) {
                  return __val;
                } else {
                  return document.createTextNode('');
                }
})()              ;
            }
            return document.createTextNode('');
})()          );
          return __el;
})()        );
        return __el;
})()      );
__el.appendChild((() => {        
if (useNativeRenderer        ) {
return (() => {            
            const __el = document.createElement('div');
            __el.setAttribute('className', 'text-[10px] font-bold text-sky-300 bg-sky-950/70 px-4 py-2 border-l-2 border-sky-400 shadow-xl backdrop-blur-md');
__el.appendChild(document.createTextNode('PICK:')            );
__el.appendChild((() => {              
if (nativeSelection.hit              ) {
return (() => {                  
const __val = null                  ;
                  if (typeof __val === 'string' || typeof __val === 'number') {
                    return document.createTextNode(String(__val));
                  } else if (__val instanceof Node) {
                    return __val;
                  } else {
                    return document.createTextNode('');
                  }
})()                ;
              } else {
return (() => {                  
const __val = "NO-HIT"                  ;
                  if (typeof __val === 'string' || typeof __val === 'number') {
                    return document.createTextNode(String(__val));
                  } else if (__val instanceof Node) {
                    return __val;
                  } else {
                    return document.createTextNode('');
                  }
})()                ;
              }
              return document.createTextNode('');
})()            );
            return __el;
})()          ;
        }
        return document.createTextNode('');
})()      );
      return __el;
})()    );
    return __el;
})()]}))  ;
}

