version = "1"
registry_kind = "visual_scripting"

[[graphs]]
id = "player.interaction.graph"
entry = "begin"
source = "sources/game/scripts/player_interaction.kain"
outputs = ["event.interact", "event.dialogue.begin"]

[[graphs]]
id = "camera.shake.graph"
entry = "on_damage"
source = "sources/game/scripts/camera_shake.kain"
outputs = ["camera.impulse"]

[[graphs]]
id = "ai.simple_patrol.graph"
entry = "spawn"
source = "sources/game/scripts/ai_patrol.kain"
outputs = ["actor.move_to", "actor.wait"]
