/**
 * MatcapPicker.tsx
 *
 * Drop-in matcap selector for KSculpt.
 * Shows a grid of visual sphere swatches generated by matcapSystem.
 * Triggered by clicking the current matcap swatch in the TopBar.
 */

import React, { useEffect, useRef, useState, useMemo, useCallback } from 'react';
import * as Popover from '@radix-ui/react-popover';
import { MATCAP_LIBRARY, getMatcapPreviewDataURL } from '../matcapSystem';
import { Check } from 'lucide-react';

interface MatcapPickerProps {
    currentMatCap: string;
    onSelect: (id: string) => void;
}

// Swatch — renders one matcap preview and handles selection
const MatcapSwatch = React.memo(function MatcapSwatch({
    id, label, desc, isSelected, onSelect,
}: {
    id: string;
    label: string;
    desc: string;
    isSelected: boolean;
    onSelect: (id: string) => void;
}) {
    const [dataUrl, setDataUrl] = useState<string>('');

    useEffect(() => {
        // Defer preview generation off the first render cycle
        const handle = requestAnimationFrame(() => {
            try {
                setDataUrl(getMatcapPreviewDataURL(id, 56));
            } catch {
                // fallback: empty
            }
        });
        return () => cancelAnimationFrame(handle);
    }, [id]);

    return (
        <button
            title={`${label} — ${desc}`}
            onClick={() => onSelect(id)}
            className={`
                relative group rounded-lg overflow-hidden
                transition-all duration-150 ease-out
                focus:outline-none
                ${isSelected
                    ? 'ring-2 ring-orange-500 ring-offset-1 ring-offset-[#0a0a0a] scale-[1.06]'
                    : 'opacity-80 hover:opacity-100 hover:scale-105 hover:ring-1 hover:ring-white/20 hover:ring-offset-1 hover:ring-offset-[#0a0a0a]'
                }
            `}
        >
            {dataUrl ? (
                <img
                    src={dataUrl}
                    alt={label}
                    width={56}
                    height={56}
                    className="block rounded-lg"
                    draggable={false}
                />
            ) : (
                <div className="w-14 h-14 rounded-lg bg-white/5 animate-pulse" />
            )}

            {/* Selected checkmark */}
            {isSelected && (
                <div className="absolute bottom-1 right-1 w-4 h-4 bg-orange-500 rounded-full flex items-center justify-center shadow-lg">
                    <Check size={9} className="text-white" strokeWidth={3} />
                </div>
            )}

            {/* Label on hover */}
            <div className={`
                absolute inset-x-0 bottom-0 py-0.5
                bg-black/70 backdrop-blur-sm
                text-[8px] font-mono tracking-wider text-center text-white
                translate-y-full group-hover:translate-y-0
                transition-transform duration-150
            `}>
                {label}
            </div>
        </button>
    );
});

export function MatcapPicker({ currentMatCap, onSelect }: MatcapPickerProps) {
    const [open, setOpen] = useState(false);

    const [currentPreview, setCurrentPreview] = useState<string>('');
    useEffect(() => {
        try {
            setCurrentPreview(getMatcapPreviewDataURL(currentMatCap, 24));
        } catch { /* */ }
    }, [currentMatCap]);

    const handleSelect = useCallback((id: string) => {
        onSelect(id);
        setOpen(false);
    }, [onSelect]);

    const currentDef = useMemo(
        () => MATCAP_LIBRARY.find(m => m.id === currentMatCap),
        [currentMatCap]
    );

    return (
        <Popover.Root open={open} onOpenChange={setOpen}>
            <Popover.Trigger asChild>
                {/* Trigger button — shows current matcap preview sphere */}
                <button
                    className={`
                        flex items-center gap-1.5 px-2 py-1 rounded-md border
                        text-[10px] font-mono tracking-wider transition-all duration-100
                        ${open
                            ? 'bg-white/10 border-orange-500/50 text-orange-200'
                            : 'bg-white/5 border-white/10 text-zinc-300 hover:bg-white/8 hover:border-white/20'
                        }
                    `}
                    title="Change matcap"
                >
                    {currentPreview
                        ? <img src={currentPreview} alt="" width={18} height={18} className="rounded-full" />
                        : <div className="w-[18px] h-[18px] rounded-full bg-white/20" />
                    }
                    <span className="uppercase">{currentDef?.label ?? currentMatCap}</span>
                    <svg
                        width="8" height="5" viewBox="0 0 8 5"
                        className={`opacity-50 transition-transform ${open ? 'rotate-180' : ''}`}
                    >
                        <path d="M0 0 L4 5 L8 0" fill="none" stroke="currentColor" strokeWidth="1.5" />
                    </svg>
                </button>
            </Popover.Trigger>

            <Popover.Portal>
                <Popover.Content
                    sideOffset={8}
                    align="end"
                    className="
                        z-[9999] animate-in fade-in-0 zoom-in-98 slide-in-from-top-1 duration-150
                        bg-[#0e0e10] border border-white/10 rounded-xl shadow-2xl shadow-black/80
                        p-3 w-auto
                    "
                >
                    {/* Header */}
                    <div className="mb-2.5 px-1">
                        <p className="text-[10px] font-mono tracking-[0.15em] text-white/60 uppercase">Matcap</p>
                    </div>

                    {/* Grid */}
                    <div className="grid gap-1.5" style={{ gridTemplateColumns: 'repeat(4, 56px)' }}>
                        {MATCAP_LIBRARY.map(def => (
                            <MatcapSwatch
                                key={def.id}
                                id={def.id}
                                label={def.label}
                                desc={def.desc}
                                isSelected={currentMatCap === def.id}
                                onSelect={handleSelect}
                            />
                        ))}
                    </div>

                    {/* Current selection info */}
                    {currentDef && (
                        <div className="mt-2.5 px-1 pt-2 border-t border-white/[0.06]">
                            <p className="text-[10px] font-mono text-orange-400 uppercase tracking-wider">
                                {currentDef.label}
                            </p>
                            <p className="text-[9px] text-white/40 mt-0.5">{currentDef.desc}</p>
                        </div>
                    )}

                    <Popover.Arrow className="fill-[#0e0e10]" />
                </Popover.Content>
            </Popover.Portal>
        </Popover.Root>
    );
}

export default MatcapPicker;
