// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Debug visualization mode
 */
export type DebugMode = "None" | "Normals" | "ZeroNormals" | "Wireframe" | "All";
