// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KosState } from "./KosState";

/**
 * Responses from Bevy to specific requests
 */
export type KosResponse = "Ok" | { "Error": { message: string, } } | { "State": KosState } | { "RaycastHit": { entity_id: number, position: [number, number, number], normal: [number, number, number], } };
