// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LogLevel } from "./LogLevel";

/**
 * A single log entry
 */
export type LogEntry = { 
/**
 * Severity level
 */
level: LogLevel, 
/**
 * Log target (e.g., "kos_engine::gpu::atlas")
 */
target: string, 
/**
 * Log message content
 */
message: string, 
/**
 * Seconds since app start
 */
timestamp: number, 
/**
 * Optional frame number for correlation
 */
frame: bigint | null, };
