// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Mesh statistics
 */
export type MeshStats = { vertex_count: number, face_count: number, undo_stack_size: number, };
