// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Primitive types for spawning
 */
export type PrimitiveType = "Cube" | "Sphere" | "Plane" | "Cylinder" | "Torus" | "Monkey";
