// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Symmetry axes state
 */
export type SymmetryState = { x: boolean, y: boolean, z: boolean, };
