// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Anchor point for relative positioning
 */
export type Anchor = "TopStart" | "TopCenter" | "TopEnd" | "BottomStart" | "BottomCenter" | "BottomEnd" | "StartTop" | "StartCenter" | "StartBottom" | "EndTop" | "EndCenter" | "EndBottom";
