// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Backdrop (overlay behind modal)
 */
export type BackdropConfig = { 
/**
 * Background color (RGBA)
 */
color: [number, number, number, number], 
/**
 * Click backdrop to dismiss
 */
dismiss_on_click: boolean, 
/**
 * Blur background
 */
blur: number | null, };
