// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../../serde_json/JsonValue";

/**
 * How to turn a React event into a Bevy command
 */
export type CommandBinding = { 
/**
 * The command type to send
 */
cmd: string, 
/**
 * Static args (merged with event payload)
 */
args: JsonValue, 
/**
 * If true, group rapid-fire events into one undo transaction
 * Useful for sliders, drag operations, etc.
 */
debounce_tx: boolean, };
