// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What triggers portal dismissal
 */
export type DismissTrigger = "ClickOutside" | "Escape" | "FocusLost" | "MouseLeave" | { "Timeout": { ms: number, } };
