// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Focus and keyboard navigation configuration
 */
export type FocusConfig = { 
/**
 * Tab order (lower = earlier in tab sequence)
 * Use -1 to remove from tab order
 */
tab_index: number, 
/**
 * Focus group (Tab cycles within group)
 * Example: "properties-panel", "modal-1"
 */
group: string | null, 
/**
 * Can this element receive focus?
 */
focusable: boolean, 
/**
 * Trap focus inside this element (for modals)
 */
trap: boolean, 
/**
 * Auto-focus when mounted
 */
auto_focus: boolean, 
/**
 * Restore focus when unmounted
 */
restore_focus: boolean, };
