// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Justify content (main axis alignment)
 */
export type JustifyContent = "Start" | "Center" | "End" | "SpaceBetween" | "SpaceAround" | "SpaceEvenly";
