// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UiNode } from "./UiNode";

/**
 * A named slot that child nodes can target
 */
export type SlotDefinition = { 
/**
 * Slot name (e.g., "header", "left_panel")
 */
name: string, 
/**
 * Default content if nothing fills the slot
 */
default: Array<UiNode> | null, };
