use specta::ts;
use std::env;
use std::fs;
use std::path::Path;
use walkdir::WalkDir;

#[path = "src/kain_contract.rs"]
mod kain_contract;
#[path = "src/registry_contract.rs"]
mod registry_contract;
#[path = "src/viewport_contract.rs"]
mod viewport_contract;

fn main() {
    // 1. Get project root (we are in apps/tauri, so go up two levels)
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let tauri_dir = Path::new(&manifest_dir);
    let root = tauri_dir
        .parent()
        .and_then(|dir| dir.parent())
        .expect("Failed to get workspace root");

    // 2. Trigger rebuilds if these files change
    println!("cargo:rerun-if-changed=Cargo.toml");
    println!("cargo:rerun-if-changed=../../package.json");
    println!("cargo:rerun-if-changed=../../docs/CARGO_ARSENAL.md");
    println!("cargo:rerun-if-changed=../../docs/NPM_ARSENAL.md");
    println!("cargo:rerun-if-changed=../../DIRECTORY.md");
    println!("cargo:rerun-if-changed=src/registry_contract.rs");
    println!("cargo:rerun-if-changed=src/kain_contract.rs");
    println!("cargo:rerun-if-changed=src/viewport_contract.rs");
    println!("cargo:rerun-if-changed=src/commands/registry.rs");
    println!("cargo:rerun-if-changed=src/kain_commands.rs");
    println!("cargo:rerun-if-changed=src/commands/viewport.rs");
    println!("cargo:rerun-if-env-changed=KAIN_BIN_PATH");

    export_specta_tauri_bindings(root);

    // Sync local Kain compiler binary into bundled resources when available.
    sync_kain_binary(tauri_dir, root);

    // Default tauri build
    tauri_build::build();

    // 3. RUN THE SENTRY CHECKS
    check_rust_arsenal(tauri_dir, root);
    check_npm_arsenal(root);
    check_bevy_syntax(tauri_dir);
    check_directory_sync(root, tauri_dir);
}

fn export_specta_tauri_bindings(root: &Path) {
    use kain_contract::{
        KainCapabilityCategory, KainCliTarget, KainCompileResponse, KainHostKind,
        KainIntegrationStatus, KainRunResponse, KainRuntimeKind, KainRuntimeOutputRegistryEntry,
        KainRuntimeRegistryEntry, KainSourceDomain, KainSourceRegistryEntry,
        KainUpstreamCapabilityEntry,
    };
    use registry_contract::{
        RegistryAdapterManifest, RegistryAdapterPackageBinding, RegistryAdapterTargetSummary,
        RegistryIntegrationContract, RegistryPublicApiEntrypoint, RegistryPublicApiSummary,
        RegistrySearchRequest, RegistryWorkspaceSummary,
    };
    use viewport_contract::{
        CameraState, FrameStats, RendererMode, SelectionResult, ShadingMode, ViewportConfig,
    };
    let generated_dir = root.join("apps").join("web").join("src").join("generated");
    let generated_file = generated_dir.join("tauriRegistry.gen.ts");

    fs::create_dir_all(&generated_dir).expect("Failed to create apps/web/src/generated");

    let mut output = String::new();
    output.push_str("// AUTO-GENERATED BY apps/tauri/build.rs. DO NOT EDIT.\n");
    output.push_str("import { invoke } from '@tauri-apps/api/core';\n\n");

    append_typescript_export::<RegistryWorkspaceSummary>(&mut output);
    append_typescript_export::<RegistryAdapterTargetSummary>(&mut output);
    append_typescript_export::<RegistryAdapterPackageBinding>(&mut output);
    append_typescript_export::<RegistryAdapterManifest>(&mut output);
    append_typescript_export::<RegistryIntegrationContract>(&mut output);
    append_typescript_export::<RegistryPublicApiEntrypoint>(&mut output);
    append_typescript_export::<RegistryPublicApiSummary>(&mut output);
    append_typescript_export::<RegistrySearchRequest>(&mut output);
    append_typescript_export::<KainCliTarget>(&mut output);
    append_typescript_export::<KainSourceDomain>(&mut output);
    append_typescript_export::<kain_contract::KainRegistryTargetKind>(&mut output);
    append_typescript_export::<KainRuntimeKind>(&mut output);
    append_typescript_export::<KainHostKind>(&mut output);
    append_typescript_export::<KainCapabilityCategory>(&mut output);
    append_typescript_export::<KainIntegrationStatus>(&mut output);
    append_typescript_export::<KainCompileResponse>(&mut output);
    append_typescript_export::<KainRunResponse>(&mut output);
    append_typescript_export::<KainSourceRegistryEntry>(&mut output);
    append_typescript_export::<KainRuntimeOutputRegistryEntry>(&mut output);
    append_typescript_export::<KainRuntimeRegistryEntry>(&mut output);
    append_typescript_export::<KainUpstreamCapabilityEntry>(&mut output);
    append_typescript_export::<RendererMode>(&mut output);
    append_typescript_export::<ShadingMode>(&mut output);
    append_typescript_export::<ViewportConfig>(&mut output);
    append_typescript_export::<CameraState>(&mut output);
    append_typescript_export::<SelectionResult>(&mut output);
    append_typescript_export::<FrameStats>(&mut output);

    append_registry_wrappers(&mut output);
    append_kain_wrappers(&mut output);
    append_viewport_wrappers(&mut output);

    fs::write(&generated_file, output).expect("Failed to write Specta Tauri bindings");
}

fn append_typescript_export<T: specta::NamedType>(output: &mut String) {
    let export_config = ts::ExportConfiguration::new().bigint(ts::BigIntExportBehavior::Number);
    output.push_str(&ts::export::<T>(&export_config).expect("Specta TS export should succeed"));
    output.push_str("\n\n");
}

fn append_registry_wrappers(output: &mut String) {
    output.push_str(
        "export async function registryGetWorkspaceSummary(): Promise<RegistryWorkspaceSummary> {\n",
    );
    output
        .push_str("  return invoke<RegistryWorkspaceSummary>('registry_get_workspace_summary');\n");
    output.push_str("}\n\n");

    output.push_str(
        "export async function registryListAdapterTargets(): Promise<RegistryAdapterTargetSummary[]> {\n",
    );
    output.push_str(
        "  return invoke<RegistryAdapterTargetSummary[]>('registry_list_adapter_targets');\n",
    );
    output.push_str("}\n\n");

    output.push_str(
        "export async function registryGetAdapterManifest(adapterTarget: string): Promise<RegistryAdapterManifest> {\n",
    );
    output.push_str(
        "  return invoke<RegistryAdapterManifest>('registry_get_adapter_manifest', { adapterTarget });\n",
    );
    output.push_str("}\n\n");

    output.push_str(
        "export async function registryGetIntegrationContract(packageName: string): Promise<RegistryIntegrationContract> {\n",
    );
    output.push_str(
        "  return invoke<RegistryIntegrationContract>('registry_get_integration_contract', { packageName });\n",
    );
    output.push_str("}\n\n");

    output.push_str(
        "export async function registryListIntegrationContracts(request?: RegistrySearchRequest): Promise<RegistryIntegrationContract[]> {\n",
    );
    output.push_str(
        "  return invoke<RegistryIntegrationContract[]>('registry_list_integration_contracts', { request });\n",
    );
    output.push_str("}\n\n");

    output.push_str(
        "export async function registryGetPublicApiSummary(packageName: string): Promise<RegistryPublicApiSummary> {\n",
    );
    output.push_str(
        "  return invoke<RegistryPublicApiSummary>('registry_get_public_api_summary', { packageName });\n",
    );
    output.push_str("}\n\n");
}

fn append_kain_wrappers(output: &mut String) {
    output.push_str(
        "export async function kainCompile(source: string, target: KainCliTarget, outputName = 'kain_output', verbose = false, strict = false): Promise<KainCompileResponse> {\n",
    );
    output.push_str(
        "  return invoke<KainCompileResponse>('kain_compile', { source, target, outputName, verbose, strict });\n",
    );
    output.push_str("}\n\n");

    output.push_str(
        "export async function kainRun(source: string, verbose = false): Promise<KainRunResponse> {\n",
    );
    output.push_str("  return invoke<KainRunResponse>('kain_run', { source, verbose });\n");
    output.push_str("}\n\n");

    output.push_str(
        "export async function kainBuildFile(path: string, target: KainCliTarget, output?: string | null): Promise<KainCompileResponse> {\n",
    );
    output.push_str(
        "  return invoke<KainCompileResponse>('kain_build_file', { path, target, output });\n",
    );
    output.push_str("}\n\n");

    output.push_str(
        "export async function kainListSources(): Promise<KainSourceRegistryEntry[]> {\n",
    );
    output.push_str("  return invoke<KainSourceRegistryEntry[]>('kain_list_sources');\n");
    output.push_str("}\n\n");

    output.push_str(
        "export async function kainListRuntimeApps(): Promise<KainRuntimeRegistryEntry[]> {\n",
    );
    output.push_str("  return invoke<KainRuntimeRegistryEntry[]>('kain_list_runtime_apps');\n");
    output.push_str("}\n\n");

    output.push_str(
        "export async function kainListUpstreamCapabilities(): Promise<KainUpstreamCapabilityEntry[]> {\n",
    );
    output.push_str(
        "  return invoke<KainUpstreamCapabilityEntry[]>('kain_list_upstream_capabilities');\n",
    );
    output.push_str("}\n\n");

    output.push_str("export async function kainReadSource(path: string): Promise<string> {\n");
    output.push_str("  return invoke<string>('kain_read_source', { path });\n");
    output.push_str("}\n\n");

    output.push_str(
        "export async function kainWriteSource(path: string, source: string): Promise<void> {\n",
    );
    output.push_str("  return invoke<void>('kain_write_source', { path, source });\n");
    output.push_str("}\n\n");
}

fn append_viewport_wrappers(output: &mut String) {
    output.push_str(
        "export async function viewportCreate(config: ViewportConfig): Promise<number> {\n",
    );
    output.push_str("  return invoke<number>('viewport_create', { config });\n");
    output.push_str("}\n\n");

    output.push_str("export async function viewportDispose(viewport: number): Promise<void> {\n");
    output.push_str("  return invoke<void>('viewport_dispose', { viewport });\n");
    output.push_str("}\n\n");

    output.push_str(
        "export async function viewportAttachMesh(viewport: number, mesh: number): Promise<number> {\n",
    );
    output.push_str("  return invoke<number>('viewport_attach_mesh', { viewport, mesh });\n");
    output.push_str("}\n\n");

    output.push_str(
        "export async function viewportDetachMesh(viewport: number, renderMesh: number): Promise<void> {\n",
    );
    output.push_str("  return invoke<void>('viewport_detach_mesh', { viewport, renderMesh });\n");
    output.push_str("}\n\n");

    output.push_str(
        "export async function viewportSetCamera(viewport: number, camera: CameraState): Promise<void> {\n",
    );
    output.push_str("  return invoke<void>('viewport_set_camera', { viewport, camera });\n");
    output.push_str("}\n\n");

    output.push_str(
        "export async function viewportRequestRedraw(viewport: number): Promise<void> {\n",
    );
    output.push_str("  return invoke<void>('viewport_request_redraw', { viewport });\n");
    output.push_str("}\n\n");

    output.push_str(
        "export async function viewportRequestSelection(viewport: number, ndcX: number, ndcY: number): Promise<SelectionResult> {\n",
    );
    output.push_str(
        "  return invoke<SelectionResult>('viewport_request_selection', { viewport, ndcX, ndcY });\n",
    );
    output.push_str("}\n\n");

    output.push_str(
        "export async function viewportGetStats(viewport: number): Promise<FrameStats> {\n",
    );
    output.push_str("  return invoke<FrameStats>('viewport_get_stats', { viewport });\n");
    output.push_str("}\n\n");

    output.push_str(
        "export async function viewportSyncSculptMesh(viewport: number, sculptHandle: number): Promise<number> {\n",
    );
    output.push_str(
        "  return invoke<number>('viewport_sync_sculpt_mesh', { viewport, sculptHandle });\n",
    );
    output.push_str("}\n\n");

    output.push_str(
        "export async function viewportSyncSceneMesh(viewport: number, mesh: number): Promise<number> {\n",
    );
    output.push_str("  return invoke<number>('viewport_sync_scene_mesh', { viewport, mesh });\n");
    output.push_str("}\n\n");

    output
        .push_str("export async function viewportMarkMeshDirty(mesh: number): Promise<number> {\n");
    output.push_str("  return invoke<number>('viewport_mark_mesh_dirty', { mesh });\n");
    output.push_str("}\n\n");

    output.push_str(
        "export async function viewportSyncPrimitive(viewport: number, primitiveId: string): Promise<void> {\n",
    );
    output
        .push_str("  return invoke<void>('viewport_sync_primitive', { viewport, primitiveId });\n");
    output.push_str("}\n\n");
}

fn sync_kain_binary(tauri_dir: &Path, root: &Path) {
    let mut source_candidates: Vec<String> = Vec::new();
    if let Ok(env_path) = env::var("KAIN_BIN_PATH") {
        if !env_path.trim().is_empty() {
            source_candidates.push(env_path);
        }
    }
    if let Ok(kain_root) = env::var("KAIN_REPO_ROOT") {
        if !kain_root.trim().is_empty() {
            source_candidates.push(format!("{}/target/release/kain", kain_root.trim()));
            source_candidates.push(format!("{}/target/release/kain.exe", kain_root.trim()));
        }
    }
    source_candidates.push(
        root.join("../../Kain/target/release/kain")
            .display()
            .to_string(),
    );
    source_candidates.push(
        root.join("../../Kain/target/release/kain.exe")
            .display()
            .to_string(),
    );
    source_candidates.push("M:/code/target/release/kain.exe".to_string());
    source_candidates.push("M:/Code/target/release/kain.exe".to_string());
    source_candidates.push("M:/code/Kain/target/release/kain.exe".to_string());
    source_candidates.push("M:/Code/Kain/target/release/kain.exe".to_string());

    let source = source_candidates
        .iter()
        .map(Path::new)
        .find(|path| path.exists())
        .map(|path| path.to_path_buf());

    let Some(source_path) = source else {
        println!(
            "cargo:warning=Kain binary not found. Set KAIN_BIN_PATH or place a built kain binary in ../../Kain/target/release"
        );
        return;
    };

    let target_dir = tauri_dir.join("resources").join("bin");
    let target_file_name = source_path
        .file_name()
        .and_then(|name| name.to_str())
        .unwrap_or(if cfg!(windows) { "kain.exe" } else { "kain" });
    let target_path = target_dir.join(target_file_name);

    if let Err(err) = fs::create_dir_all(&target_dir) {
        println!(
            "cargo:warning=Failed to create Kain resource directory: {}",
            err
        );
        return;
    }

    let should_copy = match (fs::metadata(&source_path), fs::metadata(&target_path)) {
        (Ok(src), Ok(dst)) => src.len() != dst.len() || src.modified().ok() > dst.modified().ok(),
        (Ok(_), Err(_)) => true,
        (Err(_), _) => false,
    };

    if !should_copy {
        return;
    }

    match fs::copy(&source_path, &target_path) {
        Ok(_) => println!(
            "cargo:warning=Bundled Kain binary synced: {} -> {}",
            source_path.display(),
            target_path.display()
        ),
        Err(err) => println!(
            "cargo:warning=Failed to copy Kain binary ({} -> {}): {}",
            source_path.display(),
            target_path.display(),
            err
        ),
    }
}

fn check_rust_arsenal(tauri_dir: &Path, root: &Path) {
    let cargo_path = tauri_dir.join("Cargo.toml");
    let arsenal_path = root.join("docs").join("CARGO_ARSENAL.md");

    if !arsenal_path.exists() {
        panic!("CARGO_ARSENAL.md missing! Create it in the root to pass The Sentry.");
    }

    let cargo_content = fs::read_to_string(cargo_path).expect("Failed to read Cargo.toml");
    let arsenal_content =
        fs::read_to_string(arsenal_path).expect("Failed to read CARGO_ARSENAL.md");

    let cargo_toml: toml::Value =
        toml::from_str(&cargo_content).expect("Failed to parse Cargo.toml");

    let mut missing_crates = Vec::new();

    if let Some(deps) = cargo_toml.get("dependencies").and_then(|d| d.as_table()) {
        for (crate_name, _) in deps {
            if !arsenal_content.contains(crate_name) {
                missing_crates.push(crate_name.to_string());
            }
        }
    }

    if !missing_crates.is_empty() {
        panic!(
            "\n\n\
            \x1b[1;31m=============================================================\n\
            🛑 SENTRY PROTOCOL: BUILD BLOCKED BY UNDOCUMENTED CRATES 🛑\n\
            =============================================================\x1b[0m\n\
            \n\
            [ATTENTION AI AGENT / SCAVENGER KING]\n\
            You added the following Rust crates to Cargo.toml but did NOT\n\
            document them in 'CARGO_ARSENAL.md':\n\
            \n\
            {:#?}\n\
            \n\
            [INSTRUCTION FOR AGENT]\n\
            1. READ Cargo.toml\n\
            2. OPEN CARGO_ARSENAL.md in the root\n\
            3. ADD a row for these crates explaining their purpose.\n\
            4. RETRY THE BUILD.\n\
            \n\
            DO NOT IGNORE THIS. THE BUILD WILL FAIL UNTIL DOCS ARE SYNCED.\n\
            =============================================================\n\n",
            missing_crates
        );
    }
}

fn check_npm_arsenal(root: &Path) {
    let package_path = root.join("package.json");
    let arsenal_path = root.join("docs").join("NPM_ARSENAL.md");

    if !package_path.exists() {
        return;
    }
    if !arsenal_path.exists() {
        panic!("NPM_ARSENAL.md missing! Create it in the root to pass The Sentry.");
    }

    let package_content = fs::read_to_string(package_path).expect("Failed to read package.json");
    let arsenal_content = fs::read_to_string(arsenal_path).unwrap_or_default();

    let package_json: serde_json::Value =
        serde_json::from_str(&package_content).expect("Failed to parse package.json");

    let mut missing_packages = Vec::new();

    if let Some(deps) = package_json.get("dependencies").and_then(|d| d.as_object()) {
        for (pkg_name, _) in deps {
            if !arsenal_content.contains(pkg_name) {
                missing_packages.push(pkg_name.to_string());
            }
        }
    }

    if !missing_packages.is_empty() {
        panic!(
            "\n\n\
            \x1b[1;31m=============================================================\n\
            🛑 SENTRY PROTOCOL: BUILD BLOCKED BY UNDOCUMENTED NPM PACKAGES 🛑\n\
            =============================================================\x1b[0m\n\
            \n\
            [ATTENTION AI AGENT]\n\
            You installed new NPM packages but ignored 'NPM_ARSENAL.md'.\n\
            \n\
            MISSING PACKAGES:\n\
            {:#?}\n\
            \n\
            [ACTION REQUIRED]\n\
            UPDATE NPM_ARSENAL.md IMMEDIATELY OR THE BUILD WILL NOT PASS.\n\
            =============================================================\n\n",
            missing_packages
        );
    }
}

/// Check for deprecated Bevy 0.14/0.15/0.16 syntax patterns
fn check_bevy_syntax(tauri_dir: &Path) {
    let forbidden_patterns: Vec<(&str, &str)> = vec![
        // Bundles (deprecated in 0.15)
        (
            "PbrBundle",
            "Use (Mesh3d, MeshMaterial3d, Transform) tuple instead",
        ),
        (
            "MaterialMeshBundle",
            "Use (Mesh3d, MeshMaterial3d, Transform) tuple instead",
        ),
        (
            "MaterialMesh2dBundle",
            "Use (Mesh2d, MeshMaterial2d, Transform) tuple instead",
        ),
        (
            "SpriteBundle",
            "Use Sprite component directly (auto-inserts required components)",
        ),
        ("SpriteSheetBundle", "Use Sprite component directly"),
        ("NodeBundle", "Use Node component directly"),
        ("TextBundle", "Use Text component directly"),
        ("Text2dBundle", "Use Text2d component directly"),
        ("ButtonBundle", "Use Button component directly"),
        ("ImageBundle", "Use ImageNode component directly"),
        ("Camera2dBundle", "Use Camera2d component directly"),
        ("Camera3dBundle", "Use Camera3d component directly"),
        ("PointLightBundle", "Use PointLight component directly"),
        (
            "DirectionalLightBundle",
            "Use DirectionalLight component directly",
        ),
        ("SpotLightBundle", "Use SpotLight component directly"),
        (
            "SpatialBundle",
            "Use Transform component directly (deprecated)",
        ),
        ("VisibilityBundle", "Use Visibility component directly"),
        // Events -> Messages (0.17)
        ("EventReader<", "Use MessageReader<T> instead (Bevy 0.17)"),
        ("EventWriter<", "Use MessageWriter<T> instead (Bevy 0.17)"),
        ("Events<", "Use Messages<T> instead (Bevy 0.17)"),
        ("add_event::<", "Use add_message::<T>() instead (Bevy 0.17)"),
        ("send_event(", "Use write_message() instead (Bevy 0.17)"),
        // Observers (0.17)
        ("Trigger<", "Use On<T> instead (Bevy 0.17)"),
        ("OnAdd", "Use Add instead (Bevy 0.17 - On prefix removed)"),
        ("OnInsert", "Use Insert instead (Bevy 0.17)"),
        ("OnRemove", "Use Remove instead (Bevy 0.17)"),
        ("OnDespawn", "Use Despawn instead (Bevy 0.17)"),
        ("trigger_targets(", "Use trigger() instead (Bevy 0.17)"),
        // Asset handles
        ("Handle::Weak", "Use Handle::Uuid instead (Bevy 0.17)"),
        ("weak_handle!", "Use uuid_handle! instead (Bevy 0.17)"),
    ];

    let src_dir = tauri_dir.join("src");
    let mut violations: Vec<(String, String, String)> = Vec::new();

    for entry in WalkDir::new(&src_dir)
        .into_iter()
        .filter_map(|e| e.ok())
        .filter(|e| e.path().extension().map_or(false, |ext| ext == "rs"))
    {
        let content = match fs::read_to_string(entry.path()) {
            Ok(c) => c,
            Err(_) => continue,
        };

        for (pattern, fix) in &forbidden_patterns {
            if content.contains(pattern) {
                // Skip if it's in a comment (basic check)
                let in_comment = content.lines().any(|line| {
                    let trimmed = line.trim();
                    (trimmed.starts_with("//")
                        || trimmed.starts_with("*")
                        || trimmed.starts_with("/*"))
                        && line.contains(pattern)
                });

                if !in_comment {
                    violations.push((
                        entry
                            .path()
                            .strip_prefix(tauri_dir)
                            .unwrap_or(entry.path())
                            .display()
                            .to_string(),
                        pattern.to_string(),
                        fix.to_string(),
                    ));
                }
            }
        }
    }

    if !violations.is_empty() {
        let mut msg = String::new();
        for (file, pattern, fix) in &violations {
            msg.push_str(&format!(
                "  {} -> '{}'\n    FIX: {}\n\n",
                file, pattern, fix
            ));
        }

        panic!(
            "\n\n\
            \x1b[1;31m=============================================================\n\
            🛑 SENTRY PROTOCOL: DEPRECATED BEVY SYNTAX DETECTED 🛑\n\
            =============================================================\x1b[0m\n\
            \n\
            [ATTENTION AI AGENT]\n\
            You are using OUTDATED Bevy patterns. This project uses Bevy 0.17!\n\
            \n\
            VIOLATIONS FOUND:\n\
            {}\n\
            [CRITICAL]\n\
            DO NOT use Bevy 0.14/0.15/0.16 patterns. Check CARGO_ARSENAL.md\n\
            for correct Bevy 0.17 syntax.\n\
            =============================================================\n\n",
            msg
        );
    }
}

/// Check for new files not documented in DIRECTORY.md (warning only, doesn't block)
fn check_directory_sync(root: &Path, tauri_dir: &Path) {
    let directory_path = root.join("DIRECTORY.md");

    if !directory_path.exists() {
        println!("cargo:warning=DIRECTORY.md missing! Create it for The Sentry to track files.");
        return;
    }

    let directory_content = fs::read_to_string(&directory_path).unwrap_or_default();
    let mut undocumented: Vec<String> = Vec::new();

    // Check Rust modules in apps/tauri/src/
    let rust_src = tauri_dir.join("src");
    for entry in WalkDir::new(&rust_src)
        .max_depth(2) // Only top-level modules
        .into_iter()
        .filter_map(|e| e.ok())
        .filter(|e| e.path().extension().map_or(false, |ext| ext == "rs"))
    {
        let filename = entry.path().file_name().unwrap().to_string_lossy();
        // Skip mod.rs and main.rs, they're implicit
        if filename == "mod.rs" || filename == "main.rs" || filename == "lib.rs" {
            continue;
        }
        let module_name = filename.trim_end_matches(".rs");
        if !directory_content.contains(module_name) {
            let rel_path = entry.path().strip_prefix(root).unwrap_or(entry.path());
            undocumented.push(format!("  [RUST] {}", rel_path.display()));
        }
    }

    // Check React apps in apps/web/src/apps/
    let apps_dir = root.join("apps").join("web").join("src").join("apps");
    if apps_dir.exists() {
        for entry in WalkDir::new(&apps_dir)
            .max_depth(3)
            .into_iter()
            .filter_map(|e| e.ok())
            .filter(|e| {
                e.path().is_dir()
                    && e.path()
                        .file_name()
                        .map_or(false, |n| n.to_string_lossy().starts_with("K"))
            })
        {
            let dir_name = entry.path().file_name().unwrap().to_string_lossy();
            if !directory_content.contains(&*dir_name) {
                let rel_path = entry.path().strip_prefix(root).unwrap_or(entry.path());
                undocumented.push(format!("  [APP]  {}", rel_path.display()));
            }
        }
    }

    // Check Python scripts in sources/python/
    let python_dir = root.join("sources/python");
    if python_dir.exists() {
        for entry in WalkDir::new(&python_dir)
            .max_depth(3)
            .into_iter()
            .filter_map(|e| e.ok())
            .filter(|e| e.path().extension().map_or(false, |ext| ext == "py"))
        {
            let filename = entry.path().file_name().unwrap().to_string_lossy();
            // Skip __init__.py and common utility names
            if filename == "__init__.py" || filename == "__main__.py" {
                continue;
            }
            let script_name = filename.trim_end_matches(".py");
            if !directory_content.contains(script_name) {
                let rel_path = entry.path().strip_prefix(root).unwrap_or(entry.path());
                undocumented.push(format!("  [PY]   {}", rel_path.display()));
            }
        }
    }

    // Print warning if undocumented files found
    if !undocumented.is_empty() {
        println!("cargo:warning=");
        println!(
            "cargo:warning=📁 SENTRY: {} files not documented in DIRECTORY.md:",
            undocumented.len()
        );
        for item in &undocumented {
            println!("cargo:warning={}", item);
        }
        println!("cargo:warning=");
        println!("cargo:warning=Consider adding these to DIRECTORY.md for AI agent clarity.");
        println!("cargo:warning=");
    }
}
