// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Individual debug overlay types
 */
export type DebugOverlay = "Normals" | "ZeroNormals" | "Wireframe" | "BoundingBoxes";
