// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BrushLibrary } from "./BrushLibrary";
import type { LayerHierarchy } from "./LayerHierarchy";
import type { SculptState } from "./SculptState";
import type { ViewportState } from "./ViewportState";

/**
 * The complete application state - synced every frame or on change
 */
export type KosState = { viewport: ViewportState, sculpt: SculptState, layers: LayerHierarchy, brush_library: BrushLibrary, 
/**
 * Frame number for delta tracking
 */
frame: bigint, };
