// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Log severity level
 */
export type LogLevel = "Trace" | "Debug" | "Info" | "Warn" | "Error";
