// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MeshStats } from "./MeshStats";
import type { SymmetryState } from "./SymmetryState";

/**
 * Complete sculpt tool state - synced between Bevy and React
 */
export type SculptState = { 
/**
 * Currently active brush ID
 */
active_brush: string, 
/**
 * Brush radius in world units
 */
radius: number, 
/**
 * Brush intensity/strength (0.0 - 1.0)
 */
intensity: number, 
/**
 * Add mode (true) or subtract mode (false)
 */
is_add: boolean, 
/**
 * Symmetry settings
 */
symmetry: SymmetryState, 
/**
 * Current mesh stats
 */
mesh_stats: MeshStats, 
/**
 * Performance info
 */
fps: number, };
