// Generated by KAIN Compiler (Project Ouroboros)
// Do not edit - regenerate from .kn source

#![allow(unused_variables)]
#![allow(unused_mut)]
#![allow(dead_code)]
#![allow(unused_parens)]

use std::collections::{HashMap, HashSet};
use std::rc::Rc;
use std::cell::{Cell, RefCell};
use std::sync::{Arc, Mutex, RwLock};
use std::borrow::Cow;
use std::mem::{size_of, ManuallyDrop, MaybeUninit};
use std::pin::Pin;
use std::cmp::min;
use std::ffi::c_void;
use std::fmt::Formatter;

unsafe extern "C" {
    fn malloc(size: usize) -> *mut c_void;
    fn calloc(count: usize, size: usize) -> *mut c_void;
    fn realloc(ptr: *mut c_void, size: usize) -> *mut c_void;
}
fn __kain_pow(left: f64, right: f64) -> f64 {
    left.powf(right)
}
fn __kain_alloc_bytes(size: usize, zeroed: bool) -> *mut u8 {
    unsafe {
        if zeroed { calloc(1, size) as *mut u8 } else { malloc(size) as *mut u8 }
    }
}
fn __kain_realloc_bytes(ptr: *mut u8, size: usize, _zeroed_new: bool) -> *mut u8 {
    unsafe { realloc(ptr.cast::<c_void>(), size) as *mut u8 }
}

fn __kain_union_wrap<TObject: Copy, TValue: Copy>(mut value: TObject, _active: &str, _type_key: &str, byte_size: i64, union_size: i64, active_value: TValue) -> TObject {
    let zero_span = min(union_size.max(0) as usize, size_of::<TObject>());
    let copy_span = min(min(byte_size.max(0) as usize, union_size.max(0) as usize), min(size_of::<TObject>(), size_of::<TValue>()));
    unsafe {
        std::ptr::write_bytes((&mut value as *mut TObject).cast::<u8>(), 0, zero_span);
        if copy_span > 0 { std::ptr::copy_nonoverlapping((&active_value as *const TValue).cast::<u8>(), (&mut value as *mut TObject).cast::<u8>(), copy_span); }
    }
    value
}
fn __kain_union_get<TObject: Copy, TValue: Copy>(value: TObject, _field: &str, _type_key: &str, byte_size: i64, union_size: i64, fallback: TValue) -> TValue {
    let mut result = fallback;
    let copy_span = min(min(byte_size.max(0) as usize, union_size.max(0) as usize), min(size_of::<TObject>(), size_of::<TValue>()));
    unsafe { if copy_span > 0 { std::ptr::copy_nonoverlapping((&value as *const TObject).cast::<u8>(), (&mut result as *mut TValue).cast::<u8>(), copy_span); } }
    result
}
fn __kain_union_set<TObject: Copy, TValue: Copy>(mut value: TObject, _field: &str, _type_key: &str, byte_size: i64, union_size: i64, next: TValue) -> TValue {
    let zero_span = min(union_size.max(0) as usize, size_of::<TObject>());
    let copy_span = min(min(byte_size.max(0) as usize, union_size.max(0) as usize), min(size_of::<TObject>(), size_of::<TValue>()));
    unsafe {
        std::ptr::write_bytes((&mut value as *mut TObject).cast::<u8>(), 0, zero_span);
        if copy_span > 0 { std::ptr::copy_nonoverlapping((&next as *const TValue).cast::<u8>(), (&mut value as *mut TObject).cast::<u8>(), copy_span); }
    }
    next
}
fn __kain_load_bitfield_unit<T: Copy>(value: &T, unit_offset: i64) -> u64 {
    if unit_offset < 0 || unit_offset as usize >= size_of::<T>() { return 0; }
    let mut unit = 0u64;
    let available = min(8usize, size_of::<T>() - unit_offset as usize);
    unsafe { std::ptr::copy_nonoverlapping((value as *const T).cast::<u8>().add(unit_offset as usize), (&mut unit as *mut u64).cast::<u8>(), available); }
    unit
}
fn __kain_store_bitfield_unit<T: Copy>(value: &mut T, unit_offset: i64, unit: u64) {
    if unit_offset < 0 || unit_offset as usize >= size_of::<T>() { return; }
    let available = min(8usize, size_of::<T>() - unit_offset as usize);
    unsafe { std::ptr::copy_nonoverlapping((&unit as *const u64).cast::<u8>(), (value as *mut T).cast::<u8>().add(unit_offset as usize), available); }
}
fn __kain_bitfield_mask(width: i64) -> u64 { if width <= 0 { 0 } else if width >= 64 { u64::MAX } else { (1u64 << width) - 1 } }
fn __kain_sign_extend(value: u64, width: i64) -> i64 { if width <= 0 { 0 } else if width >= 64 { value as i64 } else { let sign_bit = 1u64 << (width - 1); if (value & sign_bit) == 0 { value as i64 } else { (value | !__kain_bitfield_mask(width)) as i64 } } }
fn __kain_bitfield_get<T: Copy>(value: T, _field: &str, unit_offset: i64, bit_offset: i64, width: i64, is_signed: bool, _promoted_bits: i64) -> i64 {
    let mask = __kain_bitfield_mask(width);
    let unit = __kain_load_bitfield_unit(&value, unit_offset);
    let shifted = if bit_offset <= 0 { unit } else { unit >> bit_offset };
    let encoded = shifted & mask;
    if is_signed { __kain_sign_extend(encoded, width) } else { encoded as i64 }
}
fn __kain_bitfield_set<T: Copy, TValue: Copy + Into<i64>>(mut value: T, _field: &str, unit_offset: i64, bit_offset: i64, width: i64, is_signed: bool, promoted_bits: i64, next: TValue) -> TValue {
    let mask = __kain_bitfield_mask(width);
    let mut unit = __kain_load_bitfield_unit(&value, unit_offset);
    let encoded = (next.into() as u64) & mask;
    let shifted_mask = if bit_offset <= 0 { mask } else { mask << bit_offset };
    unit = (unit & !shifted_mask) | if bit_offset <= 0 { encoded } else { encoded << bit_offset };
    __kain_store_bitfield_unit(&mut value, unit_offset, unit);
    let _ = __kain_bitfield_get(value, "", unit_offset, bit_offset, width, is_signed, promoted_bits);
    next
}

#[derive(Debug, Clone, PartialEq)]
struct WgpuDevice {
    pub handle: Ptr<()>,
}

#[derive(Debug, Clone, PartialEq)]
struct WgpuQueue {
    pub handle: Ptr<()>,
}

#[derive(Debug, Clone, PartialEq)]
struct WgpuBuffer {
    pub handle: Ptr<()>,
    pub size: u64,
    pub usage: u64,
}

#[derive(Debug, Clone, PartialEq)]
struct WgpuTexture {
    pub handle: Ptr<()>,
    pub width: u64,
    pub height: u64,
    pub format: u64,
}

#[derive(Debug, Clone, PartialEq)]
struct WgpuSampler {
    pub handle: Ptr<()>,
}

#[derive(Debug, Clone, PartialEq)]
struct WgpuBindGroup {
    pub handle: Ptr<()>,
}

#[derive(Debug, Clone, PartialEq)]
struct WgpuBindGroupLayout {
    pub handle: Ptr<()>,
}

#[derive(Debug, Clone, PartialEq)]
struct WgpuPipelineLayout {
    pub handle: Ptr<()>,
}

#[derive(Debug, Clone, PartialEq)]
struct WgpuComputePipeline {
    pub handle: Ptr<()>,
    pub shader_module: Ptr<()>,
}

#[derive(Debug, Clone, PartialEq)]
struct WgpuCommandEncoder {
    pub handle: Ptr<()>,
}

#[derive(Debug, Clone, PartialEq)]
struct WgpuComputePass {
    pub handle: Ptr<()>,
}

#[derive(Debug, Clone, PartialEq)]
struct PbrMaterialParams {
    pub base_color: Vec4,
    pub metallic_factor: f64,
    pub roughness_factor: f64,
    pub emissive_strength: f64,
    pub normal_strength: f64,
    pub ao_strength: f64,
}

#[derive(Debug, Clone, PartialEq)]
struct SceneParams {
    pub camera_position: Vec4,
    pub sun_direction: Vec4,
    pub sun_color: Vec4,
    pub sun_intensity: f64,
    pub ambient_color: Vec3,
}

#[derive(Debug, Clone, PartialEq)]
struct ViewportParams {
    pub width: u64,
    pub height: u64,
}

#[derive(Debug, Clone, PartialEq)]
struct PbrTextureSet {
    pub albedo: WgpuTexture,
    pub normal: WgpuTexture,
    pub metallic: WgpuTexture,
    pub roughness: WgpuTexture,
    pub ao: WgpuTexture,
    pub emissive: WgpuTexture,
    pub texture_sampler: WgpuSampler,
}

#[derive(Debug, Clone, PartialEq)]
struct MaterialPipelineConfig {
    pub enable_normal_mapping: bool,
    pub enable_ao: bool,
    pub enable_emissive: bool,
    pub high_quality: bool,
    pub workgroup_size_x: u64,
    pub workgroup_size_y: u64,
}

impl MaterialPipelineConfig {
    fn create_default() -> MaterialPipelineConfig {
        let config = MaterialPipelineConfig();
        config.enable_normal_mapping = true;
        config.enable_ao = true;
        config.enable_emissive = true;
        config.high_quality = false;
        config.workgroup_size_x = 8;
        config.workgroup_size_y = 8;
        return config;
    }
}

#[derive(Debug, Clone, PartialEq)]
struct MaterialRuntime {
    pub device: WgpuDevice,
    pub queue: WgpuQueue,
    pub pipeline: WgpuComputePipeline,
    pub bind_group_layout: WgpuBindGroupLayout,
    pub pipeline_layout: WgpuPipelineLayout,
    pub config: MaterialPipelineConfig,
    pub positions_buffer: WgpuBuffer,
    pub normals_buffer: WgpuBuffer,
    pub uvs_buffer: WgpuBuffer,
    pub tangents_buffer: WgpuBuffer,
    pub color_output_buffer: WgpuBuffer,
    pub material_params_buffer: WgpuBuffer,
    pub scene_params_buffer: WgpuBuffer,
    pub viewport_params_buffer: WgpuBuffer,
    pub textures: PbrTextureSet,
    pub bind_group: Option<WgpuBindGroup>,
}

impl MaterialRuntime {
    fn create_runtime(device: WgpuDevice, queue: WgpuQueue, spirv_bytes: Vec<u64>, config: MaterialPipelineConfig) -> MaterialRuntime {
        let shader_module = create_shader_module(device, spirv_bytes);
        let bind_group_layout = create_bind_group_layout(device);
        let pipeline_layout = create_pipeline_layout(device, bind_group_layout);
        let pipeline = create_compute_pipeline(device, shader_module, pipeline_layout, config);
        let runtime = MaterialRuntime();
        runtime.device = device;
        runtime.queue = queue;
        runtime.pipeline = pipeline;
        runtime.bind_group_layout = bind_group_layout;
        runtime.pipeline_layout = pipeline_layout;
        runtime.config = config;
        runtime.positions_buffer = create_empty_buffer();
        runtime.normals_buffer = create_empty_buffer();
        runtime.uvs_buffer = create_empty_buffer();
        runtime.tangents_buffer = create_empty_buffer();
        runtime.color_output_buffer = create_empty_buffer();
        runtime.material_params_buffer = create_empty_buffer();
        runtime.scene_params_buffer = create_empty_buffer();
        runtime.viewport_params_buffer = create_empty_buffer();
        runtime.textures = create_default_textures(device);
        runtime.bind_group = None;
        return runtime;
    }
}

impl MaterialRuntime {
    fn upload_gbuffer(mut self: _, positions: Vec<Vec4>, normals: Vec<Vec4>, uvs: Vec<Vec4>, tangents: Vec<Vec4>) {
        self.positions_buffer = create_storage_buffer_vec4(self.device, self.queue, positions);
        self.normals_buffer = create_storage_buffer_vec4(self.device, self.queue, normals);
        self.uvs_buffer = create_storage_buffer_vec4(self.device, self.queue, uvs);
        self.tangents_buffer = create_storage_buffer_vec4(self.device, self.queue, tangents);
    }
}

impl MaterialRuntime {
    fn upload_material_params(mut self: _, params: PbrMaterialParams) {
        self.material_params_buffer = create_uniform_buffer_material(self.device, self.queue, params);
    }
}

impl MaterialRuntime {
    fn upload_scene_params(mut self: _, params: SceneParams) {
        self.scene_params_buffer = create_uniform_buffer_scene(self.device, self.queue, params);
    }
}

impl MaterialRuntime {
    fn upload_viewport_params(mut self: _, params: ViewportParams) {
        self.viewport_params_buffer = create_uniform_buffer_viewport(self.device, self.queue, params);
        let pixel_count = (((params.width) as u64) * ((params.height) as u64));
        self.color_output_buffer = create_output_buffer(self.device, pixel_count);
    }
}

impl MaterialRuntime {
    fn upload_textures(mut self: _, textures: PbrTextureSet) {
        self.textures = textures;
    }
}

impl MaterialRuntime {
    fn build_bind_group(mut self: _) {
        let bind_group = create_material_bind_group(self.device, self.bind_group_layout, self.positions_buffer, self.normals_buffer, self.uvs_buffer, self.tangents_buffer, self.textures, self.material_params_buffer, self.scene_params_buffer, self.viewport_params_buffer, self.color_output_buffer);
        self.bind_group = Some(bind_group);
    }
}

impl MaterialRuntime {
    fn execute(self: _, viewport_width: u64, viewport_height: u64) -> Vec<Vec4> {
        match self.bind_group { None => self.build_bind_group(), _ => { let __empty = 0; } }
        let encoder = create_command_encoder(self.device);
        let compute_pass_handle = begin_compute_pass(encoder);
        set_pipeline(compute_pass_handle, self.pipeline);
        set_bind_group(compute_pass_handle, 0, self.bind_group);
        let workgroup_count_x = ((((viewport_width + self.config.workgroup_size_x) - 1)) / self.config.workgroup_size_x);
        let workgroup_count_y = ((((viewport_height + self.config.workgroup_size_y) - 1)) / self.config.workgroup_size_y);
        dispatch_workgroups(compute_pass_handle, workgroup_count_x, workgroup_count_y, 1);
        end_compute_pass(compute_pass_handle);
        let command_buffer = finish_encoder(encoder);
        submit_command_buffer(self.queue, command_buffer);
        return read_buffer_vec4(self.device, self.queue, self.color_output_buffer, (((viewport_width) as u64) * ((viewport_height) as u64)));
    }
}

fn create_shader_module(device: WgpuDevice, spirv_bytes: Vec<u64>) -> Ptr<()> {
}

fn create_bind_group_layout(device: WgpuDevice) -> WgpuBindGroupLayout {
}

fn create_pipeline_layout(device: WgpuDevice, layout: WgpuBindGroupLayout) -> WgpuPipelineLayout {
}

fn create_compute_pipeline(device: WgpuDevice, shader: Ptr<()>, layout: WgpuPipelineLayout, config: MaterialPipelineConfig) -> WgpuComputePipeline {
}

fn create_empty_buffer() -> WgpuBuffer {
}

fn create_storage_buffer_vec4(device: WgpuDevice, queue: WgpuQueue, data: Vec<Vec4>) -> WgpuBuffer {
}

fn create_uniform_buffer_material(device: WgpuDevice, queue: WgpuQueue, data: PbrMaterialParams) -> WgpuBuffer {
}

fn create_uniform_buffer_scene(device: WgpuDevice, queue: WgpuQueue, data: SceneParams) -> WgpuBuffer {
}

fn create_uniform_buffer_viewport(device: WgpuDevice, queue: WgpuQueue, data: ViewportParams) -> WgpuBuffer {
}

fn create_output_buffer(device: WgpuDevice, pixel_count: u64) -> WgpuBuffer {
}

fn create_default_textures(device: WgpuDevice) -> PbrTextureSet {
}

fn create_material_bind_group(device: WgpuDevice, layout: WgpuBindGroupLayout, positions: WgpuBuffer, normals: WgpuBuffer, uvs: WgpuBuffer, tangents: WgpuBuffer, textures: PbrTextureSet, material_params: WgpuBuffer, scene_params: WgpuBuffer, viewport_params: WgpuBuffer, output: WgpuBuffer) -> WgpuBindGroup {
}

fn create_command_encoder(device: WgpuDevice) -> WgpuCommandEncoder {
}

fn begin_compute_pass(encoder: WgpuCommandEncoder) -> WgpuComputePass {
}

fn set_pipeline(compute_pass_handle: WgpuComputePass, pipeline: WgpuComputePipeline) {
}

fn set_bind_group(compute_pass_handle: WgpuComputePass, index: u64, bind_group: Option<WgpuBindGroup>) {
}

fn dispatch_workgroups(compute_pass_handle: WgpuComputePass, x: u64, y: u64, z: u64) {
}

fn end_compute_pass(compute_pass_handle: WgpuComputePass) {
}

fn finish_encoder(encoder: WgpuCommandEncoder) -> Ptr<()> {
}

fn submit_command_buffer(queue: WgpuQueue, command_buffer: Ptr<()>) {
}

fn read_buffer_vec4(device: WgpuDevice, queue: WgpuQueue, buffer: WgpuBuffer, count: u64) -> Vec<Vec4> {
}

