// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Active tool mode
 */
export type ActiveTool = "Viewport" | "Sculpt" | "Paint" | "Retopo";
