// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A brush asset definition
 */
export type BrushAsset = { id: string, name: string, category: string, kernel: string, 
/**
 * Optional icon path
 */
icon: string | null, };
