// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Categories of GPU errors for smarter handling
 */
export type GpuErrorCategory = "Shader" | "Buffer" | "Texture" | "Pipeline" | "Validation" | "OutOfMemory" | "DeviceLost" | "Other";
