// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActiveTool } from "./ActiveTool";
import type { BrushLibrary } from "./BrushLibrary";
import type { DebugMode } from "./DebugMode";
import type { DebugOverlay } from "./DebugOverlay";
import type { GpuErrorCategory } from "./GpuErrorCategory";
import type { AppState } from "./AppState";
import type { LayerHierarchy } from "./LayerHierarchy";
import type { LogEntry } from "./LogEntry";
import type { PrimitiveType } from "./PrimitiveType";
import type { SculptState } from "./SculptState";
import type { SymmetryState } from "./SymmetryState";
import type { UiAck } from "./krue/UiAck";
import type { UiCommand } from "./krue/UiCommand";
import type { UiPatchBatch } from "./krue/UiPatchBatch";

/**
 * All possible messages in the K-OS protocol.
 *
 * ## Adding a new message
 *
 * 1. Add a variant here
 * 2. Run `cargo test --features ts-rs` to regenerate TypeScript bindings
 * 3. That's it. No byte offsets. No manual serialization.
 *
 * ## Bevy Integration
 * 
 * When the `bevy` feature is enabled, AppMessage implements both `Event` and
 * `Message`, allowing use with EventWriter/EventReader systems.
 */
export type AppMessage = { "StateSnapshot": AppState } | { "SculptStateUpdate": SculptState } | { "LayerUpdate": LayerHierarchy } | { "BrushLibraryUpdate": BrushLibrary } | { "SetActiveTool": ActiveTool } | { "SwitchBrush": { brush_id: string, } } | { "UpdateBrushSettings": { radius: number | null, intensity: number | null, is_add: boolean | null, } } | { "SetSymmetry": SymmetryState } | "Subdivide" | { "Remesh": { resolution: number, } } | "Undo" | "Redo" | { "SelectLayer": { entity_id: number, add_to_selection: boolean, } } | { "ToggleLayerVisibility": { entity_id: number, } } | { "ToggleLayerLock": { entity_id: number, } } | { "DeleteLayer": { entity_id: number, } } | { "RenameLayer": { entity_id: number, name: string, } } | "RequestStateSnapshot" | { "WindowMove": { x: number, y: number, width: number, height: number, } } | { "CursorMove": { x: number, y: number, } } | { "MouseButton": { button: number, pressed: boolean, } } | { "Scroll": { delta_x: number, delta_y: number, } } | { "SetGizmoVisibility": { visible: boolean, } } | { "SpawnPrimitive": { primitive_type: PrimitiveType, } } | { "ImportGltf": { path: string, } } | { "LogBatch": Array<LogEntry> } | { "GpuError": { 
/**
 * The error message from WGPU
 */
error: string, 
/**
 * Error category (Shader, Buffer, Texture, Pipeline, Other)
 */
category: GpuErrorCategory, 
/**
 * Context (shader name, pipeline, etc)
 */
context: string, 
/**
 * Timestamp when error occurred
 */
timestamp: number, 
/**
 * Unique error hash for dedup
 */
error_hash: bigint, } } | { "SetDebugMode": DebugMode } | { "SetDebugOverlay": { overlay: DebugOverlay, enabled: boolean, } } | { "KrueCommand": UiCommand } | { "KruePatch": UiPatchBatch } | { "KrueAck": UiAck } | "KrueRequestSync" | "Shutdown" | "Ping" | "Pong";
