// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ObjectType } from "./ObjectType";

/**
 * A single layer/object in the scene
 */
export type LayerInfo = { 
/**
 * Bevy Entity ID (as u32)
 */
entity_id: number, 
/**
 * Display name
 */
name: string, 
/**
 * Object type
 */
object_type: ObjectType, 
/**
 * Is visible
 */
visible: boolean, 
/**
 * Is locked
 */
locked: boolean, 
/**
 * Is selected
 */
selected: boolean, };
