// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LayerInfo } from "./LayerInfo";

/**
 * Complete layer hierarchy
 */
export type LayerHierarchy = { layers: Array<LayerInfo>, 
/**
 * Primary selected entity
 */
primary_selection: number | null, };
