// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Align items (cross axis alignment)
 */
export type AlignItems = "Stretch" | "Start" | "Center" | "End" | "Baseline";
