// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UiNode } from "./UiNode";

/**
 * Virtual list configuration for large datasets
 */
export type VirtualListConfig = { 
/**
 * Binding path to total item count
 */
count_bind: string, 
/**
 * Fixed height per item (required for virtual scroll)
 */
item_height: number, 
/**
 * Number of extra items to render above/below viewport (overscan)
 */
overscan: number, 
/**
 * Template node for each item
 */
template: UiNode, 
/**
 * Binding path for the visible items data
 */
items_bind: string, 
/**
 * Optional: binding for scroll position
 */
scroll_bind: string | null, };
