version = "1"
target_platform = "windows"

inputs = [
  "src-game/assets/scenes/sandbox.kscene",
  "src-game/assets/narrative/intro.kgraph",
  "src-game/assets/gameplay/input.registry.toml",
  "src-game/assets/gameplay/tags.registry.toml",
  "src-game/assets/gameplay/actors.registry.toml",
  "src-game/assets/gameplay/cameras.registry.toml",
  "src-game/assets/gameplay/visual_scripts.registry.toml"
]

[cook]
compression = "zstd"
include_debug_names = true
strip_editor_only = false
contract_asset = "cook.contract.json"
